airbnb:
  outputs:
    dev:
      type: snowflake
      account: yrnyqbv-pf66355
      user: dbt

      role: TRANSFORM
      # Setup helper: https://dbtsetup.nordquant.com/
      private_key_passphrase: q

      database: AIRBNB
      schema: DEV
      threads: 1
      warehouse: COMPUTE_WH
  target: dev
