models:
  - name: dim_listings_cleansed
    description: "Table for listings"
    data_tests:
      - minimum_row_count:
          arguments:
            min_row_count: 1000
          config:
            severity: warn
    columns:

      - name: listing_id
        description: "id for listing"
        data_tests:
          - unique
          - not_null

      - name: host_id
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_hosts_cleansed')
                field: host_id

      - name: room_type
        data_tests:
          - accepted_values:
              arguments:
                values: [ 'Entire home/apt', 'Private room', 'Shared room', 'Hotel room' ]
      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
        data_tests:
          - positive_values

  - name: dim_hosts_cleansed
    description: "model for sving host details"
    config:
      contract:
        enforced: true
    columns:
      - name: host_id
        data_type: integer
        description: "save host id"
      - name: host_name
        data_type: string
        description: "save host name"
      - name: is_superhost
        data_type: string
      - name: updated_at
        data_type: timestamp
        description: "updated time"
      - name: created_at
        data_type: timestamp
        description: "created time"

  - name: dim_listings_w_hosts
    data_tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          arguments:
            compare_model: source('airbnb', 'listings')
    columns:
      - name: price
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: number
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              arguments:
                quantile: 0.99
                min_value: 50
                max_value: 500
          - dbt_expectations.expect_column_max_to_be_between:
              arguments:
                max_value: 5000
              config:
                severity: warn
  - name: fct_reviews
    description: Sample description for reviews
    columns:
      - name: listing_id
        data_type: number
        data_tests:
          - not_null
      - name: review_date
        data_type: timestamp_ntz
      - name: reviewer_name
        data_type: varchar
      - name: review_text
        data_type: varchar
      - name: review_sentiment
        data_type: varchar
